#!/bin/sh
# shellcheck disable=2227,2030,2031

# Author: nrv
# Description:
#   Open a tmux session inside a directory from a list.
#   Works from outside of and inside tmux, whether the server
#   is already running or not.
#   Either specify the dir, or fzf will be opened for
#   you to find it in listed directories.
#   Env vars to specify dirs are listed below.
# Credit: <https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer>

set -u

# colon-separated list like PATH
: "${TMUX_SESSIONIZER_PATH:="${HOME}/pr:${HOME}/Documents/Projects"}"
# colon-separated list of dirs to include as projects
: "${TMUX_SESSIONIZER_ADDITIONAL_DIRS:="${HOME}/dot:${HOME}/.dotfiles"}"
# default new directory location (place to create new dirs with `-c`)
: "${TMUX_SESSIONIZER_DEFAULT_DIR:="${HOME}/pr"}"

info() {
  printf >&2 'tmux-sessionizer: %s\n' "${1}"
}

usage() {
  printf >&2 'usage: tmux-sessionizer [-c] NAME\n'
  printf >&2 'options:\n'
  # shellcheck disable=2016
  printf >&2 '  -c  create directory in "${TMUX_SESSIONIZER_DEFAULT_DIR}" ("%s") if not exists\n' "${TMUX_SESSIONIZER_DEFAULT_DIR}"
}

get_all_dirs() {
  dirs="$(
    IFS=':'
    for directory in $(printf '%s' "${TMUX_SESSIONIZER_PATH}"); do
      [ -d "${directory}" ] || continue
      find 2>/dev/null "${directory}" -mindepth 1 -maxdepth 1 -type 'd'
    done
  )"
  additional_dirs="$(
    printf '%s' "${TMUX_SESSIONIZER_ADDITIONAL_DIRS}" | tr ':' '\n'
  )"

  ## guard - no dirs
  [ -z "${dirs}" ] && [ -z "${additional_dirs}" ] && return 1                  

  # print dirs
  printf '%s' "${dirs}"
  [ -n "${dirs}" ] && printf '\n'
  printf '%s' "${additional_dirs}"
}

sessionize() {
  selected_name=$(basename "${selected}" | tr . -)

  # ensure desired session exists
  if ! tmux has-session -t="${selected_name}" 2> /dev/null; then
    tmux new-session -ds "${selected_name}" -c "${selected}"
  fi

  # switch
  [ -z "${TMUX-}" ] && tmux attach -t "${selected_name}"
  [ -n "${TMUX-}" ] && tmux switch-client -t "${selected_name}"
}

create=
while :; do
  case "${1-}" in
    -h|-\?|--help) usage && exit ;;
    -c|--create) create=true ;;
    --) shift && break ;;
    -?*) info "ERROR: unknown option: '${1}'" && usage && exit 1 ;;
    *) break ;;
  esac
  shift
done

# guard - create without NAME
[ "${create}" = true ] && [ "${#}" -eq 0 ] && info 'ERROR: no NAME specified' && usage && exit 1
# FIXME: path still can be specified instead of plain name.
[ "${create}" = true ] && selected="${TMUX_SESSIONIZER_DEFAULT_DIR}/${1}" && mkdir -p "${selected}" && sessionize

# guard - no dirs
all_dirs="$(get_all_dirs)" || exit 1

# select
if [ "${#}" -ge 1 ]; then
  selected="$(
      for directory in ${all_dirs}; do
        [ "$(basename "${directory}")" = "${1}" ] &&
          printf '%s' "${directory}" &&
          break
      done
  )"
  [ -z "${selected}" ] && info "ERROR: no such project in your dirs: '${1}'" && exit 1
else
  selected=$(get_all_dirs | fzf) || exit 1
fi

sessionize
